name: flowder
description: Persistent file downloader manager, start, pause, resume, cancel your download.
version: 0.3.0
homepage: https://github.com/MSNexploder/flowder

environment:
  sdk: ">=2.19.0 <3.4.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
